# NIT_inspiral - code to rapidly compute extreme mass-ratio inspirals using self-force results
# Copyright (C) 2017  Niels Warburton
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os
env = Environment()

env['ENV']['TERM'] = os.environ['TERM']

env['LIBPATH']  = ['']
env['LIBS']     = ['gsl' , 'gslcblas', 'fftw3', 'config++']
env['CXX']      = 'g++'
env['CPPPATH']  = ['../include']
env['CXXFLAGS'] = ['-std=c++14', '-Wall', '-Wno-unused-variable', '-g', '-O2']

sources = ['NIT_inspiral.cc', 'lib_Sch_GSF.c', 'lib_Sch_geodesic.c', 'Interpolant.cc', 'EoM.cc']

env.Program('../NIT_inspiral', sources)